services:
  notification-agent:
    image: ghcr.io/${GHCR_OWNER:-tekkifox}/${GHCR_REPOSITORY:-server-maintenance-notification-agent}:${GHCR_TAG:-latest}
    env_file:
      - path: stack.env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
