services:
  notification-agent:
    image: ghcr.io/${GHCR_OWNER:-tekkifox}/${GHCR_REPOSITORY:-server-maintenance-notification-agent}:${GHCR_TAG:-latest}
    env_file:
      - path: stack.env
        required: false
    environment:
      HTTP_ADDR: :8080
    ports:
      - "8080:8080"
    restart: unless-stopped
