services:
  notification-agent:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: stack.env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
