// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Returns service health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/console/command": {
            "post": {
                "description": "Sends the provided command directly to one or more containers without templating.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Send a raw console command",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Dry run request",
                        "name": "dry_run",
                        "in": "query"
                    },
                    {
                        "description": "Raw command request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.DockerCommandRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.DockerCommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.ErrorResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/discord/broadcast": {
            "post": {
                "description": "Sends a message to one or more Discord channels.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discord"
                ],
                "summary": "Send a Discord broadcast",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Dry run request",
                        "name": "dry_run",
                        "in": "query"
                    },
                    {
                        "description": "Discord broadcast request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.TriggerRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.TriggerResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.ErrorResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/message/broadcast": {
            "post": {
                "description": "Broadcasts a game-specific message command to one or more consoles, optionally in dry-run mode.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Broadcast a message command to consoles",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Dry run request",
                        "name": "dry_run",
                        "in": "query"
                    },
                    {
                        "description": "Broadcast request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.BroadcastRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.BroadcastResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.ErrorResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_httpapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_httpapi.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "server-maintenance-notification-agent_internal_service.BroadcastDelivery": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "container_ref": {
                    "type": "string"
                },
                "game": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                },
                "sent": {
                    "type": "boolean"
                },
                "transport": {
                    "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.BroadcastTransport"
                }
            }
        },
        "server-maintenance-notification-agent_internal_service.BroadcastRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "container_id": {
                    "type": "string"
                },
                "container_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "container_name": {
                    "type": "string"
                },
                "container_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dry_run": {
                    "type": "boolean"
                },
                "game": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "rcon": {
                    "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.RCONRequest"
                },
                "transport": {
                    "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.BroadcastTransport"
                }
            }
        },
        "server-maintenance-notification-agent_internal_service.BroadcastResult": {
            "type": "object",
            "properties": {
                "deliveries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.BroadcastDelivery"
                    }
                },
                "dry_run": {
                    "type": "boolean"
                },
                "sent": {
                    "type": "boolean"
                }
            }
        },
        "server-maintenance-notification-agent_internal_service.BroadcastTransport": {
            "type": "string",
            "enum": [
                "docker",
                "rcon",
                "telnet"
            ],
            "x-enum-varnames": [
                "BroadcastTransportDocker",
                "BroadcastTransportRCON",
                "BroadcastTransportTelnet"
            ]
        },
        "server-maintenance-notification-agent_internal_service.DockerCommandRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "container_id": {
                    "type": "string"
                },
                "container_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "container_name": {
                    "type": "string"
                },
                "container_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dry_run": {
                    "type": "boolean"
                },
                "rcon": {
                    "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.RCONRequest"
                }
            }
        },
        "server-maintenance-notification-agent_internal_service.DockerCommandResult": {
            "type": "object",
            "properties": {
                "deliveries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server-maintenance-notification-agent_internal_service.BroadcastDelivery"
                    }
                },
                "dry_run": {
                    "type": "boolean"
                },
                "sent": {
                    "type": "boolean"
                }
            }
        },
        "server-maintenance-notification-agent_internal_service.RCONRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "server-maintenance-notification-agent_internal_service.TriggerRequest": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "string"
                },
                "channel_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dry_run": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "server-maintenance-notification-agent_internal_service.TriggerResult": {
            "type": "object",
            "properties": {
                "delivered": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dry_run": {
                    "type": "boolean"
                },
                "sent": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Server Maintenance Notification Agent API",
	Description:      "HTTP API for Discord maintenance notifications and remote console broadcasts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
